IF OBJECT_ID(N'dbo.tbl_news', N'U') IS NULL BEGIN
	CREATE TABLE tbl_news (
		id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		title VARCHAR(250) NOT NULL,
		headline VARCHAR(250) NOT NULL,
		image VARCHAR(MAX) NOT NULL,
		date DATETIME NOT NULL,
		article VARBINARY(MAX) NOT NULL
	);
END

IF OBJECT_ID(N'dbo.tbl_tag', N'U') IS NULL BEGIN
	CREATE TABLE tbl_tag (
	    id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		news_id INT NOT NULL FOREIGN KEY REFERENCES tbl_news(id),
		name VARCHAR(30) NOT NULL
	);
END